INSERT INTO pregnant_risk (id, description, risk) VALUES
(1, 'Baixa escolaridade (<5 anos de estudo)', 1),
(2, 'Tabagista ativo', 2),
(3, 'Indícios de ocorrência de violência', 2),
(4, 'Gestante em situação de rua ou em comunidades indígenas ou quilombola', 2),
(5, 'Baixo peso no início da gestação (IMC <18)', 2),
(6, 'Sobrepeso (25-29,9 kg)', 1),
(7, 'Obesidade (IMC > 30 – 39,9 kg)', 4),
(8, 'Obesidade grau 3', 10),

(9,'Dois abortos consecutivos ou três não consecutivos', 2),
(10, 'Prematuridade na gestação anterior', 2),
(11, 'Mais de um parto prematuro (<36 semanas)', 10),
(12, 'Restrição de crescimento intrauterino na gestação anterior', 2),
(13, 'Natimorto sem causa determinada', 10),
(14, 'Incompetência Istmo Cervical', 10),
(15, 'Isoimunização Rh (histórico)', 5),
(16, 'Pré-eclâmpsia com resultado obstétrico ruim', 10),
(17, 'Psicose puerperal na gestação anterior', 10),
(18, 'Transplante', 5),
(19, 'Cirurgia bariátrica há menos de 6 meses', 10),
(20, 'Acretismo placentário (histórico)', 2),

(21, 'Doença Hipertensiva da Gestação/Pré-eclâmpsia', 10),
(22, 'Diabetes Gestacional não compensada com dieta', 10),
(23, 'Infecção urinária de repetição(3x ou mais) ou alta', 10),
(24, 'Cálculo renal com obstrução', 10),
(25, 'Restrição de crescimento intrauterino', 10),
(26, 'Feto acima do percentil 90% ou suspeita de macrossomia', 10),
(27, 'Polidrâmnio/Oligoidrâmnio', 10),
(28, 'Colo curto em USG transvaginal entre 20 e 24 semanas', 10),
(29, 'Suspeita de acretismo placentário', 10),
(30, 'Placenta prévia após 28 semanas de gestação com ou sem sangramento', 10),
(31, 'Hepatopatias (como colestase ou elevação de transaminases)', 10),
(32, 'Anemia grave ou refratária ao tratamento', 10),
(33, 'Isoimunização RH (ativa)', 10),
(34, 'Câncer materno durante a gestação', 10),
(35, 'Neoplasias ginecológicas na gestação atual', 10),
(36, 'Alta suspeita clínica de câncer de mama', 10),
(37, 'Lesão de alto grau em colo uterino (NIC II-III)', 10),
(38, 'Suspeita de malformação fetal ou arritmia fetal', 10),
(39, 'Sífilis (terciária ou com achados ecográficos sugestivos ou resistente a tratamento)', 10),
(40, 'Condiloma acuminado extenso ou em canal vaginal/colo', 10),
(41, 'Hepatites agudas na gestação atual', 10),
(42, 'Hanseníase na gestação atual', 10),
(43, 'AIDS/HIV diagnosticado na gestação', 10),
(44, 'Tuberculose', 10),
(45, 'Toxoplasmose OU rubéola OU citomegalovírus diagnosticado na gestação atual com risco de transmissão fetal', 10),
(46, 'Dependência e/ou uso abusivo de drogas lícitas e ilícitas', 10),
(47, 'Endocrinopatias descompensadas', 10),
(48, 'Suspeita ou confirmação de dengue, zika ou chikungunya', 5),
(49, 'Suspeita ou confirmação de COVID-19', 5),
(50, 'Hipertensão arterial descompensada', 10),
(51, 'Diabetes Mellitus tipo 1 ou 2', 10),
(52, 'Tireoidopatias clínicas (hipo/hipertireoidismo)', 10),
(53, 'Doença psiquiátrica grave(como psicoses, depressão grave)', 10),
(54, 'Doenças hematológicas (anemia falciforme, PTI, PTT, talassemia, etc.)', 10),
(55, 'Cardiopatias com repercussão hemodinâmica', 10),
(56, 'Pneumopatias graves (DPOC, Asma grave)', 10),
(57, 'Doenças autoimunes (ex.: colagenose)', 10),
(58, 'Uso de medicamentos teratogênicos (ex.: anticonvulsivantes, estabilizadores de humor)', 10),
(59, 'Doença renal grave', 10),
(60, 'Hemopatias e Anemia grave (hemoglobina < 8 g/dl)', 10),
(61, 'Hepatopatias crônicas (ex.: hepatite viral, cirrose)', 10);
